export const FETCH_ARTICLES = 'NEWS-WIDGET_FETCH_ARTICLES';
export const FILTER_ARTICLES = 'NEWS-WIDGET_FILTER_ARTICLES';
export const LOAD_MORE_ARTICLES = 'NEWS-WIDGET_LOAD_MORE';
export const FETCH_ARTICLES_SUCCES = 'NEWS-WIDGET_FETCH_SUCCESS';
